name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install GNU Smalltalk
      run: sudo apt-get install gnu-smalltalk
    - uses: actions/checkout@v2
    - name: tests
      run: make test
    - name: install
      run: sudo make install
